-define(APP_NAME, erlsp).
-define(ERLSP_SERVER, erlsp_server).

%% JSON-RPC
-define(JSONRPC_SERVER_ERROR_END, -32000).
-define(JSONRPC_UNKNOWN_ERROR_CODE, -32001).
-define(JSONRPC_SERVER_NOT_INITIALIZED, -32002).
-define(JSONRPC_SERVER_ERROR_START, -32099).
-define(JSONRPC_INVALID_REQUEST, -32600).
-define(JSONRPC_METHOD_NOT_FOUND, -32601).
-define(JSONRPC_INVALID_PARAMS, -32602).
-define(JSONRPC_INTERNAL_ERROR, -32603).
-define(JSONRPC_PARSE_ERROR, -32700).
%% LSP
-define(JSONRPC_REQUEST_CANCELLED, -32800).
%% LSP TextDocumentSyncKind
-define(TEXT_DOCUMENT_SYNC_FULL, 1).
