#!/usr/bin/env node
// Tokenizes source files with the real TextMate engine (vscode-textmate +
// vscode-oniguruma) against syntaxes/erlang.tmLanguage.json and writes each
// token's scopes to a sibling `<name>.erl.tokens` file next to the fixture.

const fs = require("fs");
const path = require("path");
const oniguruma = require("vscode-oniguruma");
const vsctm = require("vscode-textmate");

const grammarPath = path.join(__dirname, "..", "syntaxes", "erlang.tmLanguage.json");
const fixturesDir = path.join(__dirname, "..", "test-fixtures");

const HEADER = [
  "# AUTOGENERATED by scripts/check-grammar.js.",
  "# DO NOT EDIT BY HAND!",
  "",
].join("\n");

function fixtureFiles() {
  return fs
    .readdirSync(fixturesDir)
    .filter((name) => name.endsWith(".erl"))
    .sort()
    .map((name) => path.join(fixturesDir, name));
}

async function loadGrammar() {
  const wasmPath = path.join(
    path.dirname(require.resolve("vscode-oniguruma/package.json")),
    "release/onig.wasm"
  );
  const wasmBin = fs.readFileSync(wasmPath).buffer;
  const onigLib = oniguruma.loadWASM(wasmBin).then(() => ({
    createOnigScanner: (patterns) => new oniguruma.OnigScanner(patterns),
    createOnigString: (s) => new oniguruma.OnigString(s),
  }));

  const registry = new vsctm.Registry({
    onigLib,
    loadGrammar: async (scopeName) => {
      if (scopeName === "source.erlang") {
        const content = fs.readFileSync(grammarPath, "utf-8");
        return vsctm.parseRawGrammar(content, grammarPath);
      }
      return null;
    },
  });

  const grammar = await registry.loadGrammar("source.erlang");
  if (!grammar) {
    console.error(`Failed to load grammar from ${grammarPath}`);
    process.exit(1);
  }
  return grammar;
}

function tokenizeFile(grammar, filePath) {
  const lines = fs.readFileSync(filePath, "utf-8").split("\n");
  let ruleStack = vsctm.INITIAL;
  const out = [HEADER];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const result = grammar.tokenizeLine(line, ruleStack);
    out.push(`Line ${i + 1}: ${line}`);
    for (const token of result.tokens) {
      const text = line.substring(token.startIndex, token.endIndex);
      out.push(`  ${JSON.stringify(text)} -> ${token.scopes.join(" ")}`);
    }
    ruleStack = result.ruleStack;
  }

  return out.join("\n") + "\n";
}

async function main() {
  const grammar = await loadGrammar();
  const targets = process.argv[2] ? [process.argv[2]] : fixtureFiles();

  if (targets.length === 0) {
    console.error(`No *.erl files found in ${fixturesDir}`);
    process.exit(1);
  }

  for (const filePath of targets) {
    const output = tokenizeFile(grammar, filePath);
    const outPath = `${filePath}.tokens`;
    fs.writeFileSync(outPath, output);
    console.log(`wrote ${path.relative(process.cwd(), outPath)}`);
  }

  console.log(`\nOK: regenerated ${targets.length} .tokens file(s).`);
}

main().catch((err) => {
  console.error("ERROR:", err);
  process.exit(1);
});
